export const AJOUTER_JOUEUR = "AJOUTER_JOUEUR";
export const AJOUTER_TITULAIR = "AJOUTER_TITULAIR";
export const AJOUTER_SUPLENT = "AJOUTER_SUPLENT";
export const SUPRIMER_TITULAIR = "SUPRIMER_TITULAIR";
export const SUPRIMER_SUPLENT = "SUPRIMER_SUPLENT";
